name: CI
on: push
jobs:
  lint-and-breaking-change-detection:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - name: Checkout
        uses: actions/checkout@v4
      # Install the `buf` CLI
      - name: Setup
        uses: bufbuild/buf-setup-action@v1.27.2
        with:
          github_token: ${{ github.token }}
      # Lint the Buf module in the `github-actions` directory
      - name: Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: projects
      # Detect breaking changes for the Buf module in the `github-actions` directory
      # against the current `main` branch
      - name: Breaking change detection against `main`
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: projects
          against: https://github.com/go-bazzinga/contracts.git#branch=main,ref=HEAD~1,subdir=github-actions